### ISSUE TITLE
Add a feature to allow emails to specific domains only.

### ISSUE THREAD

**Issue by pboling** [pboling/sanitize_email#16]
Similar to: https://github.com/osbornebrook/sanitize_email/commit/dda1f9b9d3b765359e770ad4460020b1c65a8a8d#commitcomment-4703742

**Comment by milgner** [comment]
FWIW, we implemented this with `activation_proc` for the time being:

```ruby
config[:activation_proc] = ->(message) do
  Array(message.to).any? { |recipient| Mail::Address.new(recipient).domain != 'example.com' }
end
```

**Comment by pboling** [comment]
Your example prevents sending the email if any of the recipients have a specific domain, which is the inverse of the title of this issue.  I'll add both to the README.

**Comment by pboling** [comment]
Oh, but your version is missing a `!`.

```
%w(
  me@example.com
  you@example.net
  us@example.net
).any? { |email| email.domain != "example.com" }
# => true, means it will send the email
```
Your example is the opposite of what you want I think.
