### ISSUE TITLE
Unable to sanitize BCC only email

### ISSUE THREAD

**Issue by mikecx** [pboling/sanitize_email#37]
BCC Only emails fail to send because they are missing a `to:` field based upon the following line:
https://github.com/pboling/sanitize_email/blob/master/lib/sanitize_email/overridden_addresses.rb#L46

I haven't been able to find any relevant RFC on whether BCC only emails are valid however my testing via Gmail with BCC only has worked.

**Comment by pboling** [comment]
That's interesting.  So you would suggest that we just ensure that there is at least one of :to, :cc, or :bcc?

I like the idea.  Have time to create a PR with the change?

**Comment by mikecx** [comment]
That's the most proper email validity check as far as I can tell. Looking at the tests for the code, it looks as though BCC's are filtered out entirely. If thats true it's probably a bit of a larger PR that I can take on right now but I can definitely try and get out out in the future unless someone beats me to it.

**Comment by pboling** [comment]
Will fix in next release!

**Comment by pboling** [comment]
Fixed in release 2.0.5!
