### ISSUE TITLE
HoundCI does not have the same rules as RuboCop

### ISSUE THREAD

**Issue by joeyparis** [pboling/sanitize_email#75]
HoundCI and RuboCop have conflicting rules that make committing code requests difficult as what satisfies local testing doesn't satisfy pull request testing.

I personally prefer the style choices we have set in Rubocop, but at least one of the two configurations should be updated to match each other.

**Comment by pboling** [comment]
I'll cleanup the Rubocop Style rules with next release.  Thanks for pointing it out!

**Comment by pboling** [comment]
I'm hopeful that this is resolved... but haven't tested with a PR yet.

**Comment by pboling** [comment]
I'm not sure if this is resolved, as I haven't made a PR, but if this comes up again I'll look into it.  RuboCop is much more constrained now since the addition of RuboCop-LTS.
