### ISSUE TITLE
config[:sanitized_bcc] key does not work

### ISSUE THREAD

**Issue by piousbox** [pboling/sanitize_email#97]
When configuring the gem, setting the key `config[:sanitized_bcc]` should make all sanitized emails go to config[:sanitized_to] AND to this config[:sanitized_bcc] email. However, it is not happening.

**Comment by pboling** [comment]
Thanks for the bug report.  Will fix in next release.

**Comment by pboling** [comment]
Actually, I'm not sure what you mean.  Setting `config[:sanitized_bcc]` means "I want to override the BCC field only", and other fields will not be affected.

This is useful when , for example, you want to add a BCC recipient to every email sent by a system.

**Comment by pboling** [comment]
If I am misunderstanding please describe the issue in more detail, and I'll reopen the issue!
